CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "grades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "stacks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grade_id" int,
  "stack_id" int,
  "full_name" varchar,
  "email" varchar,
  "password_hash" varchar,
  "start_date" date,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "user_roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "role_id" int
);

CREATE TABLE "competencies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" int,
  "name" varchar,
  "description" text
);

CREATE TABLE "competency_matrix" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "competency_id" int,
  "stack_id" int,
  "grade_id" int
);

CREATE TABLE "materials" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "competency_id" int,
  "title" varchar,
  "content" text,
  "link" varchar,
  "type" varchar
);

CREATE TABLE "tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "competency_id" int,
  "title" varchar,
  "description" text,
  "estimated_time_hours" int
);

CREATE TABLE "learning_programs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "creator_id" int
);

CREATE TABLE "program_tasks" (
  "program_id" int,
  "task_id" int,
  "order_index" int
);

CREATE TABLE "user_programs" (
  "user_id" int,
  "program_id" int,
  "assigned_date" date
);

CREATE TABLE "user_task_progress" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "task_id" int,
  "status" varchar,
  "actual_time_hours" int,
  "reviewer_id" int,
  "reviewer_comment" text,
  "submission_link" varchar
);

CREATE TABLE "user_competency_assessments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "competency_id" int,
  "reviewer_id" int,
  "status" varchar,
  "assessment_date" date,
  "justification" text
);

ALTER TABLE "users" ADD FOREIGN KEY ("grade_id") REFERENCES "grades" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("stack_id") REFERENCES "stacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competencies" ADD FOREIGN KEY ("parent_id") REFERENCES "competencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competency_matrix" ADD FOREIGN KEY ("competency_id") REFERENCES "competencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competency_matrix" ADD FOREIGN KEY ("stack_id") REFERENCES "stacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competency_matrix" ADD FOREIGN KEY ("grade_id") REFERENCES "grades" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "materials" ADD FOREIGN KEY ("competency_id") REFERENCES "competencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("competency_id") REFERENCES "competencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learning_programs" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "program_tasks" ADD FOREIGN KEY ("program_id") REFERENCES "learning_programs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "program_tasks" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_programs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_programs" ADD FOREIGN KEY ("program_id") REFERENCES "learning_programs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_task_progress" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_task_progress" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_task_progress" ADD FOREIGN KEY ("reviewer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_competency_assessments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_competency_assessments" ADD FOREIGN KEY ("competency_id") REFERENCES "competencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_competency_assessments" ADD FOREIGN KEY ("reviewer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
